### ISSUE TITLE
Suggestions for additional features

### ISSUE THREAD

**Issue by dlt-** [nfarina/homebridge-tesla#1]
First of all: Thanks! I just got an idea about controlling teslas cabin heating via homebridge. This works perfectly!

Here is a couple of other ideas that came to my mind:
- Using brightness control (or maybe battery status and another switch) to show charging state and to start/stop charging
- Temperature indicators for inside and outside (better than to combine them to thermostat control as it requires more clicks to activate heating)

**Comment by nfarina** [comment]
I like the temperature indicator idea! Although my values seem to be `null` - are those values only updated when the climate control is turned on?

Also, what would the benefit of manually controlling charging state be? Isn't your car typically just plugged in all the time at home with schedule-based charging for utility rate optimization?

**Comment by dlt-** [comment]
They are updated more frequently when cc is on.

Benefits for using dimmable lightbulb control for charging:

- Allows you to set charge limit (30-100%) by using dimming slider
- Shows current battery charge state (with same indicator!)

I personally do not need stop/start toggle for charging (and it could be also accomplished by just reducing target charge limit below current state), but some users may have small main circuit breakers and need to stop charging temporary to allow some other devices to be used (Sauna, for example).



By the way Is it possible to disable notifications for Locking/unlocking  ?

**Comment by nfarina** [comment]
Before the Home app, it was possible to customize HomeKit notifications more granularly - like disable just notifications for Locks, or Security Systems, etc. With the Home app, that seems to have disappeared - instead you need to turn off Notifications for the Home app altogether (which is what I've done - I've never found the notifications useful).

**Comment by dlt-** [comment]
Actually the notification setting is still there. just hold the lock icon , click details and "Status and notifications".

**Comment by nfarina** [comment]
Genius! Thanks a ton - I would never have discovered this. I have found the new Home app to be wildly confusing.

**Comment by mrose17** [comment]
@dlt - where do i find this "lock icon" of which you speak? thanks!

**Comment by dlt-** [comment]
The button in home app you use to unlock/lock the car. Just keep it pressed and a  menu opens.

**Comment by mrose17** [comment]
got it, thanks!

**Comment by dlt-** [comment]
another idea: configurable geofence (gps coordinates) which trigger "motion sensor" type event in homekit. You could then light up driveway lights by using automation features in hk.

**Comment by nfarina** [comment]
You mean light up the driveway using the Tesla headlights?

**Comment by dlt-** [comment]
No, but to activate other homekit controlled lights by triggering virtual "motion sensor" ( homekit Characteristic.MotionDetected) 

homekit automation feature lets you configure an action (to turn on some lights) which can be triggered by that motion detector

**Comment by stevesreed** [comment]
I would really like the ability to turn on/off charging.

Ultimately I'm trying to stop the Teslas from charging when the Powerwall is powering the house and there is no grid or solar available. There is a homekit plugin for the Powerwall (homebridge-tesla-powerwall) so I just need to be able turn off charging, based on the Powerwall state)

**Comment by nfarina** [comment]
Just published a new version of the plugin that exposes an on/off switch for charging. "Turn on the Model 3 Charger" will begin charging even if it's outside your schedule.

I actually personally find this useful as I park my 3 on the street and occasionally pull it into the driveway to charge in the middle of the day (usually charging is schedule for midnight).
