### ISSUE TITLE
Access to charge level?

### ISSUE THREAD

**Issue by jibberjabberish** [nfarina/homebridge-tesla#107]
The main reason I want to access my Tesla from Apple Homekit is to see the current charge level and if its 10pm, alert me that the car isn't plugged in. Sometimes I forget. It would be amazing to have this automation possible.

**Comment by nfarina** [comment]
The plugin does expose battery level but it doesn't seem like this is available in Shortcuts for automations :(

I think it would be easy to expose another "lightbulb" service where the brightness level is the car's battery level. Additionally, you could expose a "switch" service that shows whether the car is plugged in. Right now we have a switch for whether the charge port is locked, but that's a different thing.

I can look at this when I have time - or if someone wants to make a PR I'm happy to merge it sooner!

**Comment by nfarina** [comment]
This is now supported in the latest version of the plugin!
