### ISSUE TITLE
Support for Rear Trunk (implementation included)

### ISSUE THREAD

**Issue by bytepoets-mba** [nfarina/homebridge-tesla#11]
Hi!

Thanks for your work on this plugin. @dromedaryCase was so kind to implement the rear trunk I need for my Model S. Code is here: https://pastebin.com/B3VFsaP4

Please consider adding it to the plugin properly.

Thanks a lot!

**Comment by nfarina** [comment]
For sure! Will tweak it to allow closing the trunk as well for Model S/X.

**Comment by nfarina** [comment]
Added and deployed in v0.7.0. Thanks for the code!

Note that on the S/X with power liftgates, it doesn't matter whether you ask Siri to open or close the Trunk - the only thing we can do is "actuate" which means to toggle state.
