### ISSUE TITLE
Climate vs climate switch?

### ISSUE THREAD

**Issue by maisun** [nfarina/homebridge-tesla#110]
Hi,
I saw two configuration options for climate and climateswitch.
Tried to read the docs but couldn't figure out how they're supposed to work, so need some better understanding here.
Does it control the preconditioning?

Thanks in advance

**Comment by nfarina** [comment]
Oops, I forgot to add this to the README! I just added it. Pasted here:

---

## Climate Switch

By default, the climate control is exposed as a "HVAC" accessory similar to a thermostat in your home. This allows you to say things like "Set the climate to 69 degrees." If you don't need this level of control, you may prefer to expose the climate control as a simple switch. This allows you to say things like "Turn on the climate control" or "Turn off the climate control." The temperature setting will be whatever the car is already set to.

```yaml
  …
  "refreshToken": "…",
  "climateSwitch": true
}
```

**Comment by maisun** [comment]
Understood, thanks a lot!
