### ISSUE TITLE
Driver's Door

### ISSUE THREAD

**Issue by givanildo** [nfarina/homebridge-tesla#112]
First of all congratulations once again for the excellent work. incredible!! one request … opening the driver's door … would be amazing!!

**Comment by nfarina** [comment]
So I can't tell if there's an API for it: https://github.com/mseminatore/TeslaJS

I had an X myself and I don't remember being able to open the driver door remotely at all, you had to be near the vehicle.

If you can verify that there's an API to open it remotely then I can add it in!

**Comment by givanildo** [comment]
I will look for this. Congratulations and thank you for always collaborating

**Comment by givanildo** [comment]
![image](https://github.com/nfarina/homebridge-tesla/assets/8014472/0114bddb-07f5-4c60-bbf4-6db1acba6305)

**Comment by nfarina** [comment]
Oh you have a Model Y? In that case are you just wanting to unlock the car doors? Because you can do that with the plugin already…

**Comment by givanildo** [comment]
Yes I do !   
I know however...actually wanted to open the driver's door. the tesla app is capable of doing this. however I wanted to use it in homekit. this command unlocks and partially opens the door. better saying, leave her ready to pull to open, sorry for my english.

**Comment by givanildo** [comment]
I already use your plugin to unlock with gestures. it would be cool to open the door with gestures too kkkkkk

**Comment by givanildo** [comment]
https://github.com/nfarina/homebridge-tesla/assets/8014472/6752573f-626b-4046-af39-278c33806bcf

**Comment by nfarina** [comment]
Hey that's cool! How are you doing the gesture recognition?

I had no idea you could unlatch the driver door from the app! So there must be an API, now we just have to figure out what it is.

**Comment by givanildo** [comment]
Nick… you (Our Master) will get it in many ways. I, a mere mortal, used OpenCv for the door of the house and for the tesla I tested that camera from the Aqara g3. then I make the association through an automation by HomeKit. using your plugin

**Comment by givanildo** [comment]
until then there was none. but with those reports of the tesla port freezing in winter, so they solved the problem by adding this functionality

**Comment by nfarina** [comment]
Well, I did some digging and found this:

https://github.com/timdorr/tesla-api/issues/637

Unfortunately the "unlatch driver door" command only works over the Tesla App's Bluetooth connection. There is no API for it that Homebridge can use :(
