### ISSUE TITLE
Log flood of "TeslaJS error: Too Many Requests"

### ISSUE THREAD

**Issue by SimonPrinz** [nfarina/homebridge-tesla#115]
I installed the plugin and configured it per the instructions in the README.  
After a while I get flooded in the Homebridge logs with a "Too Many Requests" message. Is there a way to prevent this?

```
[7/29/2023, 11:53:25 AM] [Teapot] Vehicle data updated.
[7/29/2023, 11:53:30 AM] [Teapot] Tesla reports vehicle is online.
[7/29/2023, 11:53:30 AM] [Teapot] Getting latest vehicle data from Tesla…
[7/29/2023, 11:53:32 AM] [Teapot] Vehicle data updated.
TeslaJS error: Too Many Requests
TeslaJS error: Too Many Requests
TeslaJS error: Too Many Requests
TeslaJS error: Too Many Requests
TeslaJS error: Too Many Requests
TeslaJS error: Too Many Requests
TeslaJS error: Too Many Requests
[... and still more lines ...]
```

**Comment by crm09222** [comment]
Hi. I'm receiving the same flood of errors, often when waking the car. I guess Tesla has tightened up the rate limits a bit. Do we just need a longer pause added looping to check the car's sleep status?
