### ISSUE TITLE
Not waking up

### ISSUE THREAD

**Issue by ssllii** [nfarina/homebridge-tesla#21]
My Apple Home app indicates my Tesla states have no response.  The homebridge log shows
 Using vehicle "XXXX" with state "asleep"

And shows no sign of trying to wake up the car from homebridge.

If I wake up the car by using the Tesla app, then the Home app reports the right states.
Am I missing some config setting?

**Comment by nfarina** [comment]
I just added some more language to the README to try and clarify this issue - could you take a look at the [new section](https://github.com/nfarina/homebridge-tesla#behavior-while-sleeping) and let me know if it answers your questions?

**Comment by ssllii** [comment]
Firstly thank you very much for your prompt response.  I understand why it does not automatically try waking up the car.
I added the "connection" string to config.json and restart the service but Siri is looking for "the Model 3 Connection" in my music!  I am using systemctl to start/stop my homebridge service but I might have done something wrong since "Model 3 Connection" is not showing up at Home.  
I forgot how to turn on debug for homebridge-tesla to make sure it reads the right config.

**Comment by nfarina** [comment]
Hm yes, if the "Model 3 Connection" isn't showing up in Home app then something is wrong. When the plugin starts up, it should print out some debugging info - it should include whether or not the Connection service has been initialized. If you don't see anything related to the Connection service, perhaps your plugin needs to be updated from npm?

**Comment by ssllii** [comment]
Yes, I did not have 1.0.0.  Now I have 1.0.0, connection shows up.  
Thank you so much for your help and quick response.
homebridge-tesla rocks!

**Comment by nfarina** [comment]
Awesome, glad you got it working!
