### ISSUE TITLE
Suggestions for additional features

### ISSUE THREAD

**Issue by Christiandk1986** [nfarina/homebridge-tesla#23]
Is it possible to add support for homelink?

**Comment by nfarina** [comment]
I would wire this up as an optional Switch service that issues the `homelink` command via TeslaJS. But I don't have Homelink setup for my home so I can't really build it - I'd welcome a PR!

**Comment by focher** [comment]
After discovering a small issue in the TeslaJS Homelink API call, the developer fixed it and I've added Homelink in the Pull Request I've submitted.
