### ISSUE TITLE
Speed of the plugin

### ISSUE THREAD

**Issue by Frederik840** [nfarina/homebridge-tesla#27]
Hi @nfarina ,

First of all, really appreciate this great plugin!
I do have a question on the time that the plugin needs to update in HomeKit. It shows as non responding in HomeKit first and takes about 20-30 seconds to update. I’ve been running the plugin on a clean install of homebridge, no further plugins, fiber internet connection of 250mb/s. Is there any way to speed-up this process?

**Comment by nfarina** [comment]
So we're really limited by the speed of the MCU on the car. The car is usually "disconnected" to save battery; it only wakes up to check in with Tesla's servers every once in a while (could be a few seconds, could be a minute) to see if there are any pending commands.

We are issuing commands to Tesla's servers as fast as possible - it's just that the car doesn't check in with those servers very often unless it's already "awake". Once the car is "awake" it should respond very quickly to new commands, until it goes back to sleep.

**Comment by nfarina** [comment]
Close this unless there are any followup questions!
