### ISSUE TITLE
siri control issues. 

### ISSUE THREAD

**Issue by Tkizzy** [nfarina/homebridge-tesla#3]
Sooo, I'm having an issue where siri commands, while providing feedback in the affirmative, don't actually work. Using the buttons in control center is perfectly reliable, but not via siri. The odd thing is occasionally it will work via siri to either lock/unlock the car, but not the other way around. also, home bridge will readout the command, just not the one I want.. for example locked = false when I'm trying to ask it to lock.

Perhaps worth noting I did get these errors while installing via npm 

```
sudo npm -g install homebridge-tesla


npm WARN deprecated connect@2.30.2: connect 2.x series is deprecated

> kerberos@0.0.23 install /usr/local/lib/node_modules/homebridge-tesla/node_modules/kerberos
> (node-gyp rebuild) || (exit 0)

gyp ERR! configure error 
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/homebridge-tesla/node_modules/kerberos/build'
gyp ERR! System Darwin 16.6.0
gyp ERR! command "/usr/local/Cellar/node/8.4.0/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/homebridge-tesla/node_modules/kerberos
gyp ERR! node -v v8.4.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok 
+ homebridge-tesla@0.1.0
added 263 packages in 19.251s

```

**Comment by iRayanKhan** [comment]
Try
```
Sudo npm I -g homebridge-telsa --unsafe-perm -f
```

**Comment by nfarina** [comment]
This issue is pretty old now and I've rewritten the plugin since it was opened - if you're still having trouble with the new plugin please reopen!
