### ISSUE TITLE
Is battery percentage/mileage possible?

### ISSUE THREAD

**Issue by danshaw** [nfarina/homebridge-tesla#31]
Thanks for putting this together! Is there any way to enable a view of the battery percentage or mileage?

**Comment by nfarina** [comment]
So implementing the HomeKit "car battery" service made the plugin sort of unreliable. Hard to explain. It could be exposed as a custom characteristic, but then you couldn't ask Siri about it; you'd have to launch the Home app and poke around, and then you might as well just launch the Tesla app itself. What behavior were you hoping to achieve?

**Comment by demonbane** [comment]
I’d love to see this implemented so that I could ask Siri for the current battery status. I can’t have my car plugged in all the time at home, so I need to check the battery regularly and plug it in every week or so if it hasn’t been driven.

**Comment by Gidgidonihah** [comment]
I came looking for this same thing. I wanted to ask my HomePod how many miles my car had. Or even just the charge percentage.

**Comment by demonbane** [comment]
@nfarina When you say the car battery service made the plugin unreliable, were there issues related to exposing a BatteryLevel characteristic specifically? Or is it just that battery status could be very old if you don't wake the vehicle, and very battery-draining if you do? (just trying to gauge if it's worth me trying to work on it in the hopes of submitting a PR at some point)

**Comment by nfarina** [comment]
Well the car definitely has to be awake to read battery status, as with most API calls. So you'd need to issue a wakeup command before asking about battery. If that's not an issue for you then it might be worth a shot to add the service back in and see if it works for you. You should be able to find the implementation in the commit history!

**Comment by focher** [comment]
I have submitted a Pull Request that includes a Battery Level indicator (and Homelink support). It will *not* wake the car to read it, though, because that would kill the battery. So the car has to be awake for other reasons (or manually woken up). I've had it up for about a week and didn't see any problems like battery draining.

**Comment by focher** [comment]
This has been in the plugin since mid August. I believe this can be closed.

**Comment by nfarina** [comment]
Thanks @focher!
