### ISSUE TITLE
No Response on Home App

### ISSUE THREAD

**Issue by NHMerino** [nfarina/homebridge-tesla#32]
Hello,

I've installed this several times and I always get a No Response on the Home App.

I'm not expert on Homebridge by any means but I was able to install other plugins and not this one. This one seems to be very good. If I get it to work.

All I've done is install the Plugin via HOOBS 3.1.1 and add the Accessory like it shows in the details page.

Any help would be appreciated. Thank you

![IMG_1080](https://user-images.githubusercontent.com/58652051/70386666-d5e1ca80-19de-11ea-8425-4650bd134b31.jpeg)

**Comment by nfarina** [comment]
So seeing a "No Response" most of the time is pretty normal - the car is usually sleeping to save battery, and this plugin doesn't try to wake it up just to show the current status of thing in HomeKit. Do any of the commands work? Can you lock/unlock via the Home app for instance?

**Comment by NHMerino** [comment]
So I totally agree with you, and that’s why I like this plugin so it doesn’t wake up the car, but at the moment of the photo the car was awake and I cannot do any commands, nothing works.

**Comment by nfarina** [comment]
Got it, thanks for the clarification. Can you view the Homebridge logs of what the plugin is doing? It would be helpful to know if the plugin itself is receiving your commands—and it should print out any errors related to car communication.

**Comment by NHMerino** [comment]
I’m in Japan, about to leave to the airport but as soon as I get home I’ll send you the logs. Thank you so much for your help.

**Comment by NHMerino** [comment]
I was able to get it remotely. I had another Tesla plugin installed, I uninstalled it and rebooted to see what your plugin was doing. Here are the logs. Thank you
[logs.txt](https://github.com/nfarina/homebridge-tesla/files/3937455/logs.txt)

**Comment by nfarina** [comment]
Thanks for posting those - I see the Tesla plugin being initialized but not much after - if you can run it again, can you capture some logs of it attempting to perform some action? Like ask Siri to lock the car remotely and see what the logs say?

**Comment by NHMerino** [comment]
So I just tried what you asked and no logs on the terminal show up. Nothing happens. In the home app the show up faded and they don’t even allow me to press on them. So no commands are being received by the homebridge

**Comment by apabari** [comment]
Would it be possible to add an accessory item to manually “ping” or “wake up” the car?  This would enable someone to send a “wake command” on schedule or on demand, if the accessories aren’t responding.

**Comment by nfarina** [comment]
For a time there was a switch exposed called "connection" - you could say "Turn on the [car name] connection". I couldn't decide if it was useful, but I'd be open to adding it back in.

**Comment by Obikela88** [comment]
Got same problem as NHMerino. Any Idea or did NHMerino manage to solve his issue?

**Comment by NHMerino** [comment]
I could never find a solution. I wish I could. 

Nuno

**Comment by Obikela88** [comment]
too bad. thanks for replying so fast!

**Comment by apabari** [comment]
@nfarina - would you be able to add in the connection switch?  Sounds like it would be helpful for everyone.  Thank you!

**Comment by zwily** [comment]
When I see "Accessory is not responding", none of the switches work so I can't even try to wake it up. And I always see "Accessory is not responding", unless I wake the car up manually with the Tesla app which is not ideal.

**Comment by nfarina** [comment]
Added the Connection switch back and published to npm!

**Comment by ssllii** [comment]
I am still seeing this issue after I updated to v2.5.2.  
When I tried to turn on "Connection", nothing happens, no log entry either.
