### ISSUE TITLE
Enable / Disable Accessories

### ISSUE THREAD

**Issue by apabari** [nfarina/homebridge-tesla#33]
Hello 

Would it be possible to add flags to enable or disable what shows in HomeKit?  For example, hiding the trunk and front trunk, so that one could use Siri to “Unlock the Car” without also popping the trunk and frunk. 

Thanks!

**Comment by nfarina** [comment]
Did you try "unlock the <car name> doors"?

**Comment by apabari** [comment]
Yes.... unfortunately Siri didn't hear me say "doors" and opened the trunk and frunk, in addition to unlocking the doors. :)

**Comment by nfarina** [comment]
Ah yeah. That can happen, and it is definitely annoying. I am open to alternatives that don't involve disabling other features. I spent quite some time trying to figure out if I could avoid that problem with no success. It's a lot of trial and error with Siri.

If you'd like to disable the other locks so you can say "unlock the car" it should be an easy change to make in the code!

**Comment by apabari** [comment]
Thanks!  I’m just not familiar enough with the platform in general to understand how to modify it myself, and then test/compile/install it.... otherwise I’d give it a go myself.

**Comment by sparks3875392** [comment]
I understand that you don't want to disable features but could we have config options to optionally exclude features? There are no circumstances when I want to open the frunk by accident when the car is not local.

**Comment by nfarina** [comment]
@sparks3875392 I think that's a fine idea. Feel free to make a PR, or I can look at it next time I tinker with this plugin.
