### ISSUE TITLE
npm package incomplete

### ISSUE THREAD

**Issue by cbrandlehner** [nfarina/homebridge-tesla#34]
When  installing this plugin via npm or using 'Homebridge Config UI X', the file config.schema.json is missing. This results in inability to configure the plugin using 'Homebridge Config UI X'.

Tested with version 2.3.0

**Comment by nfarina** [comment]
Just published 2.3.1 that includes this file, also I fixed it to match the current configuration options. I don't use any tools that use this config so would appreciate if you could make a PR with any further fixes!
