### ISSUE TITLE
Performance Issues ?

### ISSUE THREAD

**Issue by apabari** [nfarina/homebridge-tesla#36]
I just rebuilt a new homebridge and have noticed that the peformance degrades significantly after installing this plugin.  Is there a way I can check logs to see what's causing the problem?

Simple example - I can turn an indoor light on/off from Homekit almost instantaneously before installing this plugin, but after installing it takes 3-5 seconds before the light will turn on.

**Comment by nfarina** [comment]
That’s extremely strange! I can’t think of any reason for that. So to confirm, if you remove the Tesla configuration from your ‘config.json’, your HomeKit performance improves again? Or do you have to uninstall the plugin entirely?

**Comment by apabari** [comment]
I removed the plugin entirely and everything seemed to go back to normal.... I’m confused!

I just set up another homebridge on a new Pi and only installed the Tesla plugin. Performance is fine for my other accessories now (on the original Pi). But my Tesla isn’t responding.... I’m going to give it another go in the morning. 

Probably a PEBKAC !!  Especially if I’m the only one reporting it.  :)

**Comment by momoz** [comment]
I also use stats.. adding this plugin has increased my phantom drain by about 10 miles per day.   Any thoughts?

**Comment by nfarina** [comment]
I would look at the logs - the plugin should be logging everything it's being asked to do by HomeKit. You should only see activity when you specifically request it personally by asking Siri to do something to the car. Or if you open the Home app and it tries to refresh the current car status.

For example, when I look at my logs I see that HomeKit only requested car status one time yesterday. Probably I opened up the Home app or something.

One thing you might try is removing the car from your "favorites" in the Home app - it's possible having it in favorites will cause HomeKit to query the car status much more often.

**Comment by momoz** [comment]
> I would look at the logs - the plugin should be logging everything it's being asked to do by HomeKit. You should only see activity when you specifically request it personally by asking Siri to do something to the car. Or if you open the Home app and it tries to refresh the current car status.
> 
> For example, when I look at my logs I see that HomeKit only requested car status one time yesterday. Probably I opened up the Home app or something.
> 
> One thing you might try is removing the car from your "favorites" in the Home app - it's possible having it in favorites will cause HomeKit to query the car status much more often.

Yeah.  It was in favorites and every time i would open the home app it would refresh.   Good call.

Thanks

**Comment by nfarina** [comment]
Closing this; feel free to reopen if it's still a problem.
