### ISSUE TITLE
Additional functionality: ChargePort

### ISSUE THREAD

**Issue by brainhunts** [nfarina/homebridge-tesla#38]
Really love the project.
Is it also possible to add a command to open the Chargeport? 
Currently I need to open the app or enter the car to release the charging cable.
I know it's possible in Teslajs so perhaps it can already be done throught the homebridge instance?

**Comment by nfarina** [comment]
Does unlocking the car release the charging cable? I can add back the command to open the charge port, just didn't want to accumulate too many different controls.

**Comment by brainhunts** [comment]
Understand it completely that you want to limit the number of controls. Unfortunately opening the doors and also stopping the charging does not release the charging cable (at least not for a model S)

**Comment by nfarina** [comment]
This is implemented now!

**Comment by brainhunts** [comment]
Thanks!!

**Comment by CalvinWalzel** [comment]
> Understand it completely that you want to limit the number of controls. Unfortunately opening the doors and also stopping the charging does not release the charging cable (at least not for a model S)

Better late than never, but holding down the button to open the trunk for a few seconds also opens the charge port/releases the charge cable 😬

**Comment by mpash** [comment]
@nfarina in this same vien - would it be possible to implement an exclude list? It would be nice to hide this tile from the Home app since I don't use it and it clutters the view with accessories.

**Comment by nfarina** [comment]
There are various configuration settings you can add to hide the services you don't need, like `disableChargePort` for this one - is that what you mean?
