### ISSUE TITLE
No Response on Home App

### ISSUE THREAD

**Issue by ecoen66** [nfarina/homebridge-tesla#39]
The same as issue #32.  It doesn't matter if the car is awake or asleep.  The Connection button does nothing, since the button doesn't appear operational when there is a No Response status on it.  I suppose I can just give up, since I have the Stats app for iOS, which enables Siri shortcuts to the car controls.

**Comment by nfarina** [comment]
Can you share the logs generated by the plugin? It should be logging all attempts it's making to communicate with the car on behalf of the Home app or Siri.

**Comment by ecoen66** [comment]
Apologies, I've been distracted lately.  I did try to generate a new Token, and that gave the same result.  However, when I use my Tesla account credentials it works fine.
