### ISSUE TITLE
"Always Connected" leads to permanent "No Response"

### ISSUE THREAD

**Issue by t6cmh** [nfarina/homebridge-tesla#4]
I have been running this plugin successfully for about a year.  Two weeks ago, I disabled "Always Connected" in my Tesla while I was on vacation, but left "enable mobile access" enabled.  When I returned, I re-enabled "Always Connected", but Homekit will no longer connect to the car.  I continue to get "No Response".  Any suggestions?  I run Homebridge on a raspberry pi and tried changing the IP address.  I also removed the Tesla accessory and re-added it, to no avail.

**Comment by nfarina** [comment]
I sort of gave up on this plugin after my unlock requests were timing out most of the time. Then I turned off "always connected" to save battery (it makes a significant difference) and now unlocking via Siri is pretty impractical.

If you figure out how to make it work, I welcome any patches!

**Comment by cbrandlehner** [comment]
There was a problem with teslams, see here: https://github.com/hjespers/teslams/issues/125
Updating this dependency to the most recent version should fix it.

**Comment by nfarina** [comment]
Oh that’s great! I’ll pull in the new version and republish.
