### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by ModMike** [nfarina/homebridge-tesla#40]
I am sure I am doing something wrong somewhere. Please be gentle, completely new to Homebridge. Here is the log:

`npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning ENODATA: Cache input stream was empty
npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
npm ERR! code EINTEGRITY
npm ERR! errno EINTEGRITY
npm ERR! Invalid response body while trying to fetch https://registry.npmjs.org/homebridge-tesla: Integrity verification failed `

**Comment by nfarina** [comment]
Hi! That is very odd…looks like an issue with npm? Are you able to install other packages from npm?

**Comment by ModMike** [comment]
I am new to Homebridge and don’t know how to use an NPM install. I just used the regular install. Do you have a tutorial you can point me to?

**Comment by ModMike** [comment]
I tried both install and NPM and both give same error. I have installed other packages with no problem

**Comment by Johndowne** [comment]
I'm not sure if I have the same problem. I have several other Homebridge plug-ins working fine and installed from npm (Docker on Synology NAS). I have checked the JSON of my config.json file.

When I try to install I get some strange messages  and then when I try to run with this accessory included in my config.json I get various errors of which this is one.

(Apologies that I am not technically knowledgeable to give a better explanation.)

[5/11/2020, 2:38:13 PM] Error: The requested accessory 'Tesla' was not registered by any plugin. | stdout
-- | --

**Comment by Johndowne** [comment]
Sorry, my fault - I hadn't done the npm install thing correctly. Working now!
