### ISSUE TITLE
Cannot find Tesla

### ISSUE THREAD

**Issue by Reevak05** [nfarina/homebridge-tesla#43]
Firstly, thanks so much for all your work on Homebridge.

The logs keeps saying `No vehicles were found matching the VIN ${vin} entered in your config.json. Available vehicles:` (there is nothing after `Available vehicles`) I have checked the VIN, username, and password and I am sure they are correct. The home app has the accessories but shows them as non-responsive. I tried using an authcode instead, but that didn't work either.

**Comment by nfarina** [comment]
I fixed the logging so that "Available vehicles" should correctly show what we have access to based on the authenticated user.
