### ISSUE TITLE
Homelink Command

### ISSUE THREAD

**Issue by focher** [nfarina/homebridge-tesla#44]
Would you consider adding a Homelink command? That is the garage door opener.

It's a straightforward POST. The only hitch is that it requires also passing the LATITUDE and LONGITUDE. I propose that these could be user specified config settings as fixed values. The API wants to check if you are physically close to one of your saved Homelink devices but it's no harm if the command gets triggered when out of range.

`POST /api/1/vehicles/{id}/command/trigger_homelink`

Parameter | Example | Description
---------- | --------- | -----------
lat|36.98765432109876|Current latitude.
lon|-77.12345678901234|Current longitude.

**Comment by nfarina** [comment]
Sure yeah, that would be great! I don't have HomeLink setup myself but I'd be happy to merge a PR for it.

**Comment by focher** [comment]
Saw that this is a dupe of #23 so will close. I did create a pull request with some code that probably will add this command.
