### ISSUE TITLE
Tesla Network outage today brought down my HomeBridge😟

### ISSUE THREAD

**Issue by Tesla-P100FX** [nfarina/homebridge-tesla#47]
My homebridge was timing out this morning trying to talk to the Tesla Network which h was down. So I could not control anything else in my home.   

Did others experience this?  Should there be a timeout in this plugin?

**Comment by nfarina** [comment]
Hm, the Tesla plugin, in theory, shouldn't have any effect on other Homebridge plugins. If you disable the Tesla plugin do your other plugins work fine?

**Comment by Tesla-P100FX** [comment]
Yes it was constantly trying to log in

9/23/2020, 8:29:05 AM [Model X] Got a login token.
9/23/2020, 8:29:05 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:09 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:09 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:09 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:09 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:09 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:09 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:09 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:09 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:09 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:09 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:09 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:16 AM [Model X] Got a login token.
9/23/2020, 8:29:19 AM [Model X] Got a login token.
9/23/2020, 8:29:19 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:20 AM [Model X] Got a login token.
9/23/2020, 8:29:20 AM [Model X] Got a login token.
9/23/2020, 8:29:24 AM [Model X] Got a login token.
9/23/2020, 8:29:24 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:24 AM [Model X] Got a login token.
9/23/2020, 8:29:24 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:24 AM [Model X] Got a login token.
9/23/2020, 8:29:24 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:24 AM [Model X] Got a login token.
9/23/2020, 8:29:24 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:24 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:24 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:24 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:24 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:24 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:24 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:24 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:24 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:24 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:24 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:24 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:25 AM [Model X] Got a login token.
9/23/2020, 8:29:25 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:28 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:29 AM [Model X] Got a login token.
9/23/2020, 8:29:29 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:30 AM [Model X] Got a login token.
9/23/2020, 8:29:30 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:30 AM [Model X] Got a login token.
9/23/2020, 8:29:30 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:34 AM [Model X] Got a login token.
9/23/2020, 8:29:34 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:34 AM [Model X] Got a login token.
9/23/2020, 8:29:35 AM [Model X] Got a login token.
9/23/2020, 8:29:35 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:38 AM [Model X] Got a login token.
9/23/2020, 8:29:38 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:40 AM [Model X] Got a login token.
9/23/2020, 8:29:40 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:40 AM [Model X] Got a login token.
9/23/2020, 8:29:40 AM [Model X] Got a login token.
9/23/2020, 8:29:40 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:40 AM [Model X] Got a login token.
9/23/2020, 8:29:41 AM [Model X] Got a login token.
9/23/2020, 8:29:41 AM [Model X] Got a login token.
9/23/2020, 8:29:41 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:44 AM [Model X] Got a login token.
9/23/2020, 8:29:44 AM [Model X] Got a login token.
9/23/2020, 8:29:44 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:44 AM [Model X] Got a login token.
9/23/2020, 8:29:44 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:44 AM [Model X] Got a login token.
9/23/2020, 8:29:45 AM [Model X] Got a login token.
9/23/2020, 8:29:45 AM [Model X] Got a login token.
9/23/2020, 8:29:45 AM [Model X] Got a login token.
9/23/2020, 8:29:46 AM [Model X] Got a login token.
9/23/2020, 8:29:46 AM [Model X] Got a login token.
9/23/2020, 8:29:46 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:48 AM [Model X] Got a login token.
9/23/2020, 8:29:48 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:48 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:48 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:48 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:48 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:48 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:48 AM [Model X] Logging into Tesla with username/password…
9/23/2020, 8:29:49 AM [Model X] Logging into Tesla with username/password…

**Comment by Tesla-P100FX** [comment]
Once removed every thing ran fine

**Comment by nfarina** [comment]
Yikes, thanks for the logs! That explains the problem—the plugin is basically overwhelming the whole system. It shouldn't be able to log in with multiple simultaneous sessions like that, but then again, this is a unique situation. I'll take a look.

**Comment by nfarina** [comment]
I just published a possible fix for the parallel logins issue - can you try it and let me know if it makes any difference?

**Comment by Tesla-P100FX** [comment]
I installed.   So far so good.  I think my X (2017) with 2.5 computer goes to sleep a lot.   It often shows as not responding.   Does the “model x connection button “ keep it awake?    For how long


Thanks

Rich

Sent from my Phone 📞, please excuse typos and amusing  autocorrects


On Sep 23, 2020, at 1:11 PM, Nick Farina <notifications@github.com> wrote:

﻿

I just published a possible fix for the parallel logins issue - can you try it and let me know if it makes any difference?

**Comment by nfarina** [comment]
The button only asks it to wake up, there's no way to specify for how long, the car decides on its own when to go back to sleep. You could rig up a system that keeps "pushing the button" and keeps the car on, but being awake is a significant drain on the battery so I wouldn't recommend it.
