### ISSUE TITLE
Request: Allow show closed garage state

### ISSUE THREAD

**Issue by Geczy** [nfarina/homebridge-tesla#50]
Can you add to always show the closed state of the garage? Right now the homekit app says "no response" or when you activate homelink, it is constantly showing a refresh status and "closing" or "opening" 

https://github.com/nfarina/homebridge-tesla/blob/a09de081d413fcdc2ce443ec087b0ea247cbc90a/src/index.ts#L227

**Comment by focher** [comment]
As I added the code for Homelink, I can confirm this is not possible. Homelink does not support the garage door state (open/closed/blocked). It is merely a button toggle behavior, so the only thing possible is to send a Homelink command. If the door is open, it closes. If the door is closed, it opens. But no state is returned by Homelink on whether it was open or closed.

**Comment by focher** [comment]
I just did a pull request to fix a different non-critical error in future Homebridge versions. The code will now always set the garage door state to CLOSED.

**Comment by focher** [comment]
Can this issue be closed as it has been implemented.
