### ISSUE TITLE
Is the teslams dependency supposed to be set to >=1.3.0?

### ISSUE THREAD

**Issue by depaulsunny** [nfarina/homebridge-tesla#6]
I'm completely new to this and I may be misunderstanding something. But my homebridge-tesla update failed because it needed teslams.

Installed teslams and it still won't install because the dependency is set to 1.3.0 or greater. The node installed version is 1.2.2 which seems to be the latest version?

**Comment by cbrandlehner** [comment]
Looks like teslams 1.3.0 has not yet been published to npm. It's available on github.

**Comment by cbrandlehner** [comment]
Please leave comments or encouragements here:
https://github.com/hjespers/teslams/issues/131

**Comment by depaulsunny** [comment]
> Looks like teslams 1.3.0 has not yet been published to npm. It's available on github.

Interesting. That makes sense. Thanks!

**Comment by nfarina** [comment]
Until the new `teslams` is published, I've republished this plugin to depend on the latest commit - long story short, if you update this plugin everything should work again.

**Comment by depaulsunny** [comment]
Thanks!
