### ISSUE TITLE
Plugin is somehow unsuable for me, get always "was slow to respond!" or "didn't respond at all!"

### ISSUE THREAD

**Issue by heutger** [nfarina/homebridge-tesla#65]
I'm on the same LAN/network using the Tesla App. My car is woken up (online), just one of the rare things without issues (or disabling everything result in just three slow issues, although HomeLink also seems not to work and writing switch states is slow again). I'm unsure on why that's not working. I now add other plugins (was the first one), e.g. I just added Automover, that works without issues.

**Comment by jrimmer** [comment]
Similar case with following message from the plugin:
![image](https://user-images.githubusercontent.com/629/132782591-c1404e8c-1416-4faf-b53a-bf6c3cb24a23.png)

**Comment by nfarina** [comment]
(one year later) The beta version should fix this for good. Would love feedback if you are still using this plugin. `npm install --global homebridge-tesla@beta`
