### ISSUE TITLE
Support for refresh token

### ISSUE THREAD

**Issue by GodOSpoons** [nfarina/homebridge-tesla#66]
User utilizes 2FA, so must use API token for authentication, but current Tesla access token only lasts for 40 days. 

Requesting support for the Tesla refresh token and ongoing maintenance of an active access token through refresh via plug-in.

**Comment by nfarina** [comment]
This should be fixed by the latest version (3.0.1) - check the README for details!

**Comment by GodOSpoons** [comment]
Updated plug-in and inserted refresh token from Tesla Token into slot. Seems to be using the refresh token to get an access token, but then that access token is unauthorized. 
![B92AC4C6-997C-4EF4-A9DB-88A39DCCE4E2](https://user-images.githubusercontent.com/80660184/141648086-e7205dee-dc79-495c-9822-ae03656975ec.jpeg)

**Comment by GodOSpoons** [comment]
I have refreshed the refresh token, logged out/in of the tool (Tesla Token) to get a new session.

**Comment by nfarina** [comment]
OK - so during my research on their new auth system, I encountered some suggestions that not all refresh tokens are created equal - I think they can be tied to different roles with difference access levels. I've only used the "Auth App for Tesla" which is in the macOS and iOS stores. Is Tesla Token the android one?
