### ISSUE TITLE
After install, message 'is slowing homebridge down' and bad response in Homekit

### ISSUE THREAD

**Issue by Rem-bo** [nfarina/homebridge-tesla#67]
Great functions and would like to use it, but after install message 'is slowing homebridge down'. And indeed bad response after that in general in Homekit. So I deactivated it and now all back to quick as before....
Would really appreciate update!

**Comment by Zsoldier** [comment]
@Rem-bo as a workaround, you can run this as a child bridge.  This'll prevent this plugin from slowing down the rest of your homebridge.
https://github.com/homebridge/homebridge/wiki/Child-Bridges
![Tesla_Child_Bridge](https://user-images.githubusercontent.com/7501186/116271141-b66f4d00-a74d-11eb-9751-74ef9f721e02.png)

**Comment by nfarina** [comment]
(one year later) The beta version should fix this for good. Would love feedback if you are still using this plugin. `npm install --global homebridge-tesla@beta`
