### ISSUE TITLE
Support for enabling/disabling Sentry mode.

### ISSUE THREAD

**Issue by rossbacher** [nfarina/homebridge-tesla#68]
I'd like to automate enabling and disabling Sentry mode and I thought doing it via HomeKit would be very convenient. Looks like this is not supported. Something for a future update maybe?

**Comment by jamesalmeida** [comment]
This would be awesome

**Comment by raffertyj** [comment]
this would be resolved with #69 if it is accepted

**Comment by nfarina** [comment]
Sentry Mode is now supported (thanks @raffertyj!)
