### ISSUE TITLE
HomeLink don‘t response

### ISSUE THREAD

**Issue by LeBaron90** [nfarina/homebridge-tesla#71]
Hi,
Great Plugin! Everything works fine, except homelink, there is no answer.
I added the geo cooridnates, but it still doesn‘t work…
![739F7C82-D9B5-4EB2-9F2E-ED3BB64390F4](https://user-images.githubusercontent.com/15858705/117516516-a8b19700-af99-11eb-8148-279b27f6787c.jpeg)

**Comment by pguich** [comment]
I have the same issue. I can control Homelink from homebridge, therefore I think the setup is correct, but in the home app, it says “no response”. Not sure what I’m doing wrong?

**Comment by rondorn** [comment]
Same here. Hopefully this can be resolved with an update. I am curious. Why do you need the location data, and how precise does it have to be to where your car is?

**Comment by nfarina** [comment]
I don't have HomeLink myself so I'm not sure how this works exactly. Perhaps @focher could chime in?

**Comment by focher** [comment]
The way Tesla has implemented Homelink from the car is to verify the car is in proximity to the Homelink device. In the car, you set your location that defines your "home" in the Homelink settings. 

When calling Tesla's Homelink API endpoint, you need to include the car's latitude and longitude so the API can verify you are in proximity to the Homelink location. The Homebridge solution I implemented uses a "kludge" by letting the user define the car's location as always being within proximity and therefore allow the API to tell the car to send the Homelink signal.
