### ISSUE TITLE
HomeKit update performance 

### ISSUE THREAD

**Issue by jredner** [nfarina/homebridge-tesla#8]
A cold start of HomeKit causes a refresh and polling of the Tesla api.  During this time homebridge accessories can say updating in the HomeKit ui for several seconds.  Is it possible to have the Tesla plugin poll asynchronously and store the required state values statically so that anytime homebridge api reads state values they are returned instantly?  Perhaps there can be an option ‘background-polling’ and when set to true it follows this behavior?

**Comment by iRayanKhan** [comment]
You mean like to cache it?

**Comment by jredner** [comment]
I was thinking more of a polling + cache strategy.  If it is polled every 5 minutes (default) or so in the background there should be a high likelihood of the correct value. CacheEnabled can also default to false if someone wants to incur the wait.

**Comment by nfarina** [comment]
Polling could work, but I would personally worry about the battery impact on the car. And would it be worth the cost? I don't find myself ever asking Siri whether the car is locked or climate is on. I only ever want to change state, that is, unlock the car or turn on climate.

**Comment by jredner** [comment]
Good question.  What would be ideal is Tesla exposing some sort of last modified time or sequence that is pushed by the vehicle.

**Comment by kcharwood** [comment]
Please do not include polling by default. That will certainly have an impact on battery. The Tesla App also supports Siri, so if you're use case is Siri I would say just stick with the Tesla App.

I think this plugin provides most value for scripting automation. For example, my Good Morning scene now turns the climate control on in the car, and its great!

**Comment by nfarina** [comment]
I'm going to close this - I think the behavior we have now is correct given that we are limited to the internet-based API which costs battery (as opposed to the local Bluetooth API which is limited to the Tesla App only).
