### ISSUE TITLE
refreshToken vs authToken

### ISSUE THREAD

**Issue by raphaeldavid** [nfarina/homebridge-tesla#80]
If it helps, I had a token problem.
In my advanced configuration, the token appears under authToken instead of refreshToken
  
            "refreshToken": "",  <<<--- put your refreshToken there
            "authToken": "",
            "username": "",
            "password": ""

**Comment by nfarina** [comment]
Yeah, I updated the README to direct people to this new property but existing users might find it confusing...maybe I should add a note about that.

**Comment by nfarina** [comment]
Updated README!
