### ISSUE TITLE
Looping on startup

### ISSUE THREAD

**Issue by boxapixels** [nfarina/homebridge-tesla#83]
I'm not able to get initialised. 
Valid refresh token. 
Valid VIN. 

Running as child bridge. 

System Information

Timezone	GMT+0200
OS	Ubuntu Bionic Beaver (18.04.5 LTS)
Hostname	homebridge
IPv4 (enp2s0)	192.168.100.242
IPv6 (enp2s0)	fe80::fa75:a4ff:fef5:bba7
Node.js Version	v16.13.1
Npm Version	V8.1.2
User	homebridge
Storage Path	/var/lib/homebridge
Config Path	/var/lib/homebridge/config.json
Service Mode	Yes

Log extract that loops forever:

12/11/2021, 10:02:45 PM] [Model X] Got an access token.
TeslaJS error: Not Found
[12/11/2021, 10:02:46 PM] [Model X] Exchanging refresh token for an access token…
[12/11/2021, 10:02:46 PM] [Model X] Got an access token.
[12/11/2021, 10:02:46 PM] [Model X] Exchanging refresh token for an access token…
[12/11/2021, 10:02:47 PM] [Model X] Got an access token.
TeslaJS error: Not Found

**Comment by boxapixels** [comment]
Running as child bridge.

**Comment by scorp323** [comment]
same here!!  can anyone help with this problem??  I've been unable to use this plugin for such a long time due to this.... it used to work so well before....

**Comment by nfarina** [comment]
It's been a long time but if you have a chance to try the new beta version, this might be resolved: `npm install --global homebridge-tesla@beta`
