### ISSUE TITLE
Defrost accessory visible even when it should be disabled

### ISSUE THREAD

**Issue by gianlucad3** [nfarina/homebridge-tesla#84]
I have "disableDefrost" set to true, yet I see the Defrost accessory exposed. HB version 1.3.8, tesla plugin 3.4.0. 
Thanks!

**Comment by raffertyj** [comment]
Can you tell me if you have disableClimate set to true also? Looking at the code it seems both have to be set to true for defrost to be disabled. 

`this.disableDefrost =
       (this.disableClimate && config["disableDefrost"]) `

**Comment by raffertyj** [comment]
created PR [86](https://github.com/nfarina/homebridge-tesla/pull/86) to fix this issue.

**Comment by gianlucad3** [comment]
disableClimate is false for me. Thanks.
