### ISSUE TITLE
Different approaches, discussion 

### ISSUE THREAD

**Issue by TeslaOwnerTips** [nfarina/homebridge-tesla#90]
From #85 

I'm writing my own bash script that basically does that.
Using TeslaFi & Webhooks
Two Scripts: A server and an updater
Server
- acts as a buffer/proxy
- Webhooks sends the TeslaFi API command to the local server instead of the TeslaFi server
- Local server always responds with success
- Local server sends the command to teslaFi in a background process so that it can immediately listen for the next command from webhooks
- If more than three commands in 60 seconds (TeslaFi limit) the delay is calculated and given to the background process
- responses to all commands are saved to a file for the updater to check
Note: Even if using the Tesla API it may be good to put a check in place to prevent spamming their server in case of a bug.

Updater
- asks the local server for a vehicle state file
- server send the request which gets saved to a file
- when the file arrives the updater then updates the webhook devices

Webhook Devices
- use http://localhost:port/<teslaFi API>
- all commands are appended with a &wake=20 this ensures success unless the vehicle can't be communicated with 
- there is an "Error" device (contact sensor) that gets activated by the updater when there are errors. The user (me) can decided what to do with that. lets see how often it gets triggered.

Logs
- all logs/error are written to the homebridge log so its easy to trace/track

I'm close to being done. I've said that for a couple of weeks :)
The two scripts will run as a service (current plan anyway.)
I'm happy to share my current work if you like.

**Comment by TeslaOwnerTips** [comment]
When asleep some states always get set off such as climate, heaters, defrost, charging, sentry…
I’m not sure what to do with temperature. 
locks, doors, windows trunk frunk, charge port get left in their last state
I’ve taken a state file and set asleep values. So if state returned is asleep read this file instead. 
One option is to use push buttons so regardless of accuracy of a state the commands get sent. However I ended up with many. Anyway they are easily changed in the config file as either switches or push buttons. 
 
 There is a state (online/asleep) switch accessory which acts as an indicator as well. 
 
I think it’s more important that the commands get sent compared to an accurate state. 

For example unlocking the doors. No harm sending the unlock command if already unlocked. But having HomeKit think it’s unlocked and not send the command is annoying. 

I think the code is debugged. Now I’m going to figure out the balance between using switches vs push buttons. Switches need accurate state updates. So using what I have over time will help determine how often the state is wrong due to say using the app or changing things in person.

**Comment by TeslaOwnerTips** [comment]
I’m tempted to try using the Tesla api again. The last time I tried it I could not refresh the token so gave up and used TeslaFi. 

It would be awesome if someone published and kept up to date a homebridge plugin that only did token acquisition and refresh. This is hardest part for us hobby programmers.

**Comment by TeslaOwnerTips** [comment]
![Uploading 5A0D5D61-3E9E-4D2B-B0B6-50709AC6496D.png…]()

**Comment by TeslaOwnerTips** [comment]
![01262DAF-06CF-4E99-97EA-AD57064C584B](https://user-images.githubusercontent.com/78335749/151488869-e85256b4-05ca-47ab-bc83-50eae8aff431.png)

**Comment by TeslaOwnerTips** [comment]
![D485271D-5257-431E-885F-E0DC3AC9F899](https://user-images.githubusercontent.com/78335749/151490023-e8ea6682-b188-4cd6-9a1a-25aac9de0fb4.jpeg)

**Comment by TeslaOwnerTips** [comment]
![0A4E3984-5334-492E-AADB-332D3DD79F6C](https://user-images.githubusercontent.com/78335749/151490050-96e30bf2-d30d-4b4a-93e3-2a688260f81e.jpeg)

**Comment by deepin125** [comment]
Looks cool, hope to use.

**Comment by TeslaOwnerTips** [comment]
It’s been running for a few days without problems.

**Comment by TeslaOwnerTips** [comment]
https://github.com/TeslaOwnerTips/homebridge-teslafied
