### ISSUE TITLE
Throttling the API calls? (540 error)

### ISSUE THREAD

**Issue by jspiro** [nfarina/homebridge-tesla#91]
It seems there's no configuration for API call frequency. I've just installed this and it DOSed my Tesla account to the point where I could not access my car at all. It kept returning 540 vehicle errors.

Could not find anyone else experiencing this though :-/

**Comment by nfarina** [comment]
I'm so sorry that happened! Someone else did post about an "infinite login loop" type situation but I haven't experienced this myself and I haven't been able to sit down and diagnose it yet. It does seem like the plugin would benefit from some basic rate limiting just in case.
