### ISSUE TITLE
Battery

### ISSUE THREAD

**Issue by dhpeter** [nfarina/homebridge-tesla#92]
There is nothing that displays battery %

**Comment by nfarina** [comment]
The Home app doesn't really surface battery status much. But you can ask Siri, "what's the battery level of the Model X?" etc.

You should also see it if you tap into the accessory and go to the configuration:

![image](https://user-images.githubusercontent.com/117280/198578342-d2b7282f-640d-4cf0-8ee8-f1ac57b65062.png)
