### ISSUE TITLE
Shortcut "Network or other communication failure occurred" 

### ISSUE THREAD

**Issue by MikeAries** [nfarina/homebridge-tesla#93]
thanks for the hard work :)
everything works good but I get this message when running a siri shortcut. The short cut goes through opening the car doors and car started but Siri announce and shows this error. see pic

![IMG_5B8303095FEC-1](https://user-images.githubusercontent.com/92901516/185721147-f8db68c3-a781-4cf9-b37e-ce3414e08655.jpeg)

**Comment by nfarina** [comment]
Oh that would be cool! But I don’t think Siri Shortcuts will be reliable unfortunately, because HomeKit can’t handle the long amount of time it can take for the car to wake up and respond to commands.

**Comment by MikeAries** [comment]
It works every time I try :)

**Comment by MikeAries** [comment]
I make Siri (in a loop) wait for the car to respond connection is open

**Comment by nfarina** [comment]
Hm, surprised that works but great! Not sure why it would be failing at that particular step - does it happen 100% of the time? If not I would suspect a timeout. Perhaps this API call takes longer than most?

**Comment by MikeAries** [comment]
Yes happens 100% of the time. Definitely timeout and most likely Shortcut is waiting for a return variable (Status if turned on or not) and not getting any answer and times out. I might debug it after this recent Apple  drama settles. I suspect a function is used and changing it to an Action might solve it.

**Comment by nfarina** [comment]
Could you try the latest version of the plugin? `npm install --global homebridge-tesla@beta` - it uses a newer version of TeslaJS (among many other changes) and it might work for you. Commands happen in the background and Siri is not made to wait more than a few seconds.

Note that the config has changed; you'll need to add `"starter": true` to get the keyless driving enabled.
