### ISSUE TITLE
HomeLink No Response

### ISSUE THREAD

**Issue by elphmorgan** [nfarina/homebridge-tesla#95]
I am seeing No Response for the Model 3 Homelink tile in Home app. What issues might cause this?
(all other features are working.)

In the log I see the following:
9/27/2022, 11:10:20 AMTesla BridgeModel 3HomeLink does not support garage door status.
9/27/2022, 11:10:20 AMTesla BridgeModel 3Always setting garage door state to closed.

My code is
{
    "accessories": [
        {
            "accessory": "Tesla",
            "name": "Model 3",
            "vin": "snip",
            "refreshToken": "snip",
            "password": "<optional, only needed for keyless driving>",
            "enableHomeLink": true,
            "waitMinutes": 2,
            "plugin_map": {
                "plugin_name": "homebridge-tesla"
            },
            "latitude": "42.27861",
            "longitude": "-83.81833"
        }
    ]
}

**Comment by nfarina** [comment]
This is "normal" as the car is often asleep, so the plugin can't communicate with it. However I am changing this behavior to cache the last known state of the car instead of returning "no response" so this will be addressed soon.

**Comment by nfarina** [comment]
The new version of the plugin shouldn't have this problem. You can try the beta if you like: `npm install --global homebridge-tesla@beta`.

**Comment by elphmorgan** [comment]
Thanks so much!
