### ISSUE TITLE
accessories name

### ISSUE THREAD

**Issue by cocapic** [nfarina/homebridge-tesla#97]
Hi,

i have a small issue with the name of accessories in home
every accessorie automaticaly created with name of the car as name of accessories
relatively tiresome to deal with 10 accesories with the same name

regards

**Comment by nfarina** [comment]
Hello, so I've noticed the Home app will aggressively rename all the services we created to be the name of the car. So you end up with a million of same-named accessories.

The only solution I know of for now is to use the Home app to go to each accessory's settings and rename it to be what you'd like. Annoying but works!

**Comment by nfarina** [comment]
Update: looks like this is a known issue: https://github.com/homebridge/homebridge/issues/3210

Closing this as it's not something I can fix here.
